---
abstract: 'Perl client for Redis 2.4 and up'
author:
  - 'Mike Friedman <friedo@friedo.com>'
build_requires:
  Encode: 0
  Module::Build: 0.3601
  Test::More: 0
  strict: 0
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300003, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Redis-Client
requires:
  Carp: 0
  Data::Dumper: 0
  IO::Socket::INET: 0
  Moose: 0
  Moose::Role: 0
  Scalar::Util: 0
  aliased: 0
  namespace::sweep: 0.003
  overload: 0
  utf8: 0
resources:
  repository: git://github.com/friedo/perl-redis-client.git
version: 0.009
